---
- name: Precompile assets
  shell: "source /home/{{ deploy_user }}/.rvm/scripts/rvm && bin/rake assets:precompile RAILS_ENV={{ env }}"
  args:
    chdir: "{{ release_dir }}"
    executable: /bin/bash

